---
- name: Update to AmzLinux nodes
  hosts: webservers

  tasks:
  - name: Copy testfile1.txt to AmzLinux
    ansible.builtin.copy:
      src: /home/ec2-user/testfile1.txt
      dest: /home/ec2-user/testfile1.txt

- name: Update to Ubuntu node
  hosts: ubuntuservers

  tasks:
  - name: Copy testfile1.txt to Ubuntu node
    ansible.builtin.copy:
      src: /home/ec2-user/testfile1.txt
      dest: /home/ubuntu/testfile1.txt
