---
- name: Copy for amazon linux
  hosts: webservers
  tasks:
    - name: copy file
      copy:
        src: /home/ec2-user/testfile1
        dest: /home/ec2-user/testfile1

- name: copy for ubuntu
  hosts: ubuntuservers
  tasks:
    - name: copy file
      copy:
        src: /home/ec2-user/testfile1
        dest: /home/ubuntu/testfile1