---
- name: Apache wget removal for webservers
  hosts: ubuntuservers
  tasks:
   - name: Uninstalling Apache
     apt:
       name: apache2
       state: absent
       update_cache: yes
   - name: Remove unwanted Apache2 packages
     apt:
       autoremove: yes
       purge: yes

- name: Apache wget removal for ubuntuserver
  hosts: webservers
  tasks:
   - name: removing apache and wget
     yum:
       pkg: ['httpd', 'wget']
       state: absent